### ISSUE TITLE
consider auto-await

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/babel-preset-firecloud#12]
see https://github.com/ziolko/babel-plugin-auto-await

**Comment by IanSavchenko** [comment]
I'm against this. This plugin will make work a code which is not supposed to work and will hide mistakes. Even with all the different magic, we have in our babel plugins, our code should be a valid JS and should behave as expected without them.

**Comment by andreineculau** [comment]
I'm not pushing for it, quite the contrary. But it is a nice find regardless, and if JS would have this pattern built-in (not too mention have the async stacktraces working!), it is my honest opinion that it would have made for simpler comprehension and simpler code.

I see an important drawback alone in the fact that you cannot make use of static type analysis.

PS: 1. code is valid JS (it simply removes the need for you to type `await` before every function 2. `should behave as expected without them.` = so you'd like to have it as a rule that this repo would not do anything beyond upcoming JS syntax/behaviour, right? I'm down with that 200%

**Comment by IanSavchenko** [comment]
> 1. code is valid JS (it simply removes the need for you to type `await` before every function

The same code without `await`s behaves completely differently. Ofc, it's a valid JS, but it's not a working JS.

> so you'd like to have it as a rule that this repo would not do anything beyond upcoming JS syntax/behaviour, right? I'm down with that 200%

I'm ok with some experiments, but they have to be obvious, not implicit or have a double meaning.

**Comment by tobiiasl** [comment]
I would prefer an eslint rule that warns me when there is no await for an async function. Perhaps babel can do that? At least for simple/obvious cases.

Relevant: "New rule: enforce async/await consistency" https://github.com/eslint/eslint/issues/9787

**Comment by tobiiasl** [comment]
Perhaps this tslint rule can help out: https://palantir.github.io/tslint/rules/no-floating-promises/

**Comment by tobiiasl** [comment]
Perhaps this is a good course of actions to avoid that devs forget to add `await` before calls to functions returning promises.

1. Code style agreement that all functions returning a promise should be prefixed with `async_`.
2. Implement eslint rule that enforces that all async functions are prefixed with `async_`.
3. Implement eslint rule that all functions that are `await`:ed for are prefixed with `async`.
3. Start using TypeScript which makes function return type obvious.
4. Implement eslint rule that enforces functions returning a promise to be prefixed with `async_`.
5. Enforce the no-floating-promises tslint rule.
